import type { Metadata } from "next";
import Link from "next/link";
import { Check, Minus } from "lucide-react";
import { MarketingShell } from "@/components/marketing/marketing-shell";
import { SectionHeading } from "@/components/marketing/section-heading";
import { Button } from "@/components/ui/button";
export const metadata: Metadata = { title: "เปรียบเทียบแพ็กเกจ", description: "เปรียบเทียบแผน Free, Starter และ Professional ของระบบ Flukex POS" };
const rows: [string, string | boolean, string | boolean, string | boolean][] = [["จำนวนสาขา", "1", "1", "สูงสุด 10"], ["จำนวนผู้ใช้", "3", "15", "100"], ["จำนวนโต๊ะ", "5", "40", "500"], ["จำนวนสินค้า", "20", "300", "2,000"], ["ออเดอร์/เดือน", "100", "5,000", "50,000"], ["POS และ QR Ordering", true, true, true], ["จอครัวและบาร์", false, true, true], ["จัดการสต็อก", false, false, true], ["รายงานขั้นสูง", false, false, true], ["สิทธิ์พนักงานละเอียด", false, false, true], ["LINE Integration (อนาคต)", false, false, true], ["Custom domain (อนาคต)", false, false, true]];
const Cell = ({ value }: { value: string | boolean }) => typeof value === "boolean" ? value ? <Check className="mx-auto size-5 text-success" aria-label="มี"/> : <Minus className="mx-auto size-5 text-muted-foreground" aria-label="ไม่มี"/> : <span>{value}</span>;
export default function ComparisonPage() { return <MarketingShell><section className="mesh-bg px-4 py-20 sm:px-6"><SectionHeading eyebrow="เปรียบเทียบแผน" title="ดูทุกข้อแตกต่างในตารางเดียว" description="Entitlement ทุกตัวควบคุมจาก configuration กลาง ไม่กระจาย hard-code ตามหน้าจอ"/></section><section className="px-4 pb-20 sm:px-6"><div className="mx-auto max-w-6xl overflow-x-auto rounded-xl border bg-card shadow-soft"><table className="w-full min-w-[720px] border-collapse text-sm"><thead><tr className="bg-muted/70"><th className="p-4 text-left">ความสามารถ</th><th className="p-4">Free</th><th className="bg-primary/5 p-4 text-primary">Starter</th><th className="p-4">Professional</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]} className="border-t"><th className="p-4 text-left font-medium">{row[0]}</th><td className="p-4 text-center"><Cell value={row[1]}/></td><td className="bg-primary/[0.025] p-4 text-center"><Cell value={row[2]}/></td><td className="p-4 text-center"><Cell value={row[3]}/></td></tr>)}</tbody></table></div><div className="mt-8 text-center"><Button size="lg" asChild><Link href="/register">เริ่มใช้ฟรี</Link></Button></div></section></MarketingShell>; }
