"use client";
import { useState } from "react";
import { GripVertical, Plus, Trash2 } from "lucide-react";
import { PageHeader } from "./page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { DEMO_TENANT_ID } from "@/data/mock-data";
import { createId } from "@/lib/utils";
import { useDemoStore } from "@/store/demo-store";
export function CategoryManager(){const categories=useDemoStore(s=>s.categories);const products=useDemoStore(s=>s.products);const save=useDemoStore(s=>s.saveCategory);const remove=useDemoStore(s=>s.removeCategory);const[open,setOpen]=useState(false);const[name,setName]=useState("");const[color,setColor]=useState("#dc2626");const add=(e:React.FormEvent)=>{e.preventDefault();const now=new Date().toISOString();save({id:createId("cat"),tenantId:DEMO_TENANT_ID,name,color,sortOrder:categories.length+1,isActive:true,createdAt:now,updatedAt:now});setOpen(false);setName("");};return <><PageHeader title="หมวดหมู่สินค้า" description="จัดกลุ่มเมนูเพื่อให้ค้นหาเร็วทั้ง POS และ QR Ordering" actions={<Button onClick={()=>setOpen(true)}><Plus/>เพิ่มหมวดหมู่</Button>}/><div className="space-y-3">{categories.map((category)=><Card key={category.id} className="flex items-center gap-4 p-4"><GripVertical className="size-5 text-muted-foreground"/><span className="size-4 rounded-full" style={{backgroundColor:category.color}}/><div className="min-w-0 flex-1"><p className="font-bold">{category.name}</p><p className="text-xs text-muted-foreground">{products.filter(p=>p.categoryId===category.id).length} สินค้า</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={category.isActive} onChange={()=>save({...category,isActive:!category.isActive,updatedAt:new Date().toISOString()})}/>แสดง</label><Button variant="ghost" size="icon" aria-label={`ลบ ${category.name}`} onClick={()=>{if(confirm(`ลบหมวด ${category.name}?`))remove(category.id)}}><Trash2/></Button></Card>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>เพิ่มหมวดหมู่</DialogTitle><DialogDescription>หมวดใหม่จะแสดงใน POS และ QR Ordering ทันที</DialogDescription></DialogHeader><form onSubmit={add} className="space-y-4"><div className="space-y-2"><Label htmlFor="category-name">ชื่อหมวดหมู่</Label><Input id="category-name" value={name} onChange={e=>setName(e.target.value)} required/></div><div className="space-y-2"><Label htmlFor="category-color">สีประจำหมวด</Label><Input id="category-color" type="color" value={color} onChange={e=>setColor(e.target.value)} className="p-1"/></div><DialogFooter><Button variant="outline" type="button" onClick={()=>setOpen(false)}>ยกเลิก</Button><Button type="submit">เพิ่มหมวดหมู่</Button></DialogFooter></form></DialogContent></Dialog></>}
