"use client";

import { useState } from "react";
import { Building2, Mail, Plus, Trash2, UserRound } from "lucide-react";
import { PageHeader } from "./page-header";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import type { UserRole } from "@/domain/types";
import { DEMO_TENANT_ID } from "@/data/mock-data";
import { createId } from "@/lib/utils";
import { useDemoStore } from "@/store/demo-store";
import { services } from "@/services/container";

export function BranchManager() {
  const branches = useDemoStore((state) => state.branches);
  const saveBranch = useDemoStore((state) => state.saveBranch);
  const removeBranch = useDemoStore((state) => state.removeBranch);
  const restaurantId = useDemoStore((state) => state.restaurants[0]?.id ?? "restaurant_sawasdee");
  const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [code,setCode]=useState("");
  const add=(e:React.FormEvent)=>{e.preventDefault(); const now=new Date().toISOString(); saveBranch({id:createId("branch"),tenantId:DEMO_TENANT_ID,restaurantId,name,code,address:"กรุงเทพมหานคร",isActive:true,createdAt:now,updatedAt:now}); setOpen(false);setName("");setCode("");void services.notifications.notify({title:"เพิ่มสาขาแล้ว",message:`สร้าง ${name} ในเดโมแล้ว`});};
  return <><PageHeader title="สาขา" description="จัดการสาขาภายใต้ Restaurant tenant เดียวกัน" actions={<Button onClick={()=>setOpen(true)}><Plus/>เพิ่มสาขา</Button>}/><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{branches.map((branch)=><Card key={branch.id} className="p-5"><div className="flex items-start justify-between gap-3"><span className="grid size-11 place-items-center rounded-xl bg-secondary text-primary"><Building2/></span><Badge variant={branch.isActive?"success":"secondary"}>{branch.isActive?"เปิดใช้งาน":"ปิดใช้งาน"}</Badge></div><h2 className="mt-4 text-lg font-bold">{branch.name}</h2><p className="text-xs text-muted-foreground">{branch.code} • {branch.address}</p><div className="mt-5 flex gap-2"><Button variant="outline" size="sm" onClick={()=>saveBranch({...branch,isActive:!branch.isActive,updatedAt:new Date().toISOString()})}>{branch.isActive?"ปิดชั่วคราว":"เปิดใช้งาน"}</Button><Button variant="ghost" size="icon" aria-label={`ลบ ${branch.name}`} onClick={()=>{if(confirm(`ลบ ${branch.name}?`))removeBranch(branch.id)}}><Trash2/></Button></div></Card>)}</div><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>เพิ่มสาขา</DialogTitle><DialogDescription>ระบบจะตรวจ maxBranches จาก entitlement ในการเชื่อม production</DialogDescription></DialogHeader><form onSubmit={add} className="space-y-4"><div className="space-y-2"><Label htmlFor="branch-name">ชื่อสาขา</Label><Input id="branch-name" value={name} onChange={(e)=>setName(e.target.value)} required/></div><div className="space-y-2"><Label htmlFor="branch-code">รหัสสาขา</Label><Input id="branch-code" value={code} onChange={(e)=>setCode(e.target.value)} required/></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>ยกเลิก</Button><Button type="submit">เพิ่มสาขา</Button></DialogFooter></form></DialogContent></Dialog></>;
}

export function EmployeeManager() {
  const users=useDemoStore((state)=>state.users); const saveUser=useDemoStore((state)=>state.saveUser); const removeUser=useDemoStore((state)=>state.removeUser); const [open,setOpen]=useState(false); const [name,setName]=useState(""); const [email,setEmail]=useState(""); const [role,setRole]=useState<UserRole>("CASHIER");
  const add=(e:React.FormEvent)=>{e.preventDefault();const now=new Date().toISOString();saveUser({id:createId("user"),tenantId:DEMO_TENANT_ID,name,email,role,branchIds:["branch_sukhumvit"],createdAt:now,updatedAt:now});setOpen(false);setName("");setEmail("");void services.notifications.notify({title:"เพิ่มพนักงานแล้ว",message:`${name} พร้อมใช้งานในเดโม`});};
  return <><PageHeader title="พนักงาน" description="บัญชีจำลองและบทบาทของผู้ใช้ในร้าน" actions={<Button onClick={()=>setOpen(true)}><Plus/>เพิ่มพนักงาน</Button>}/><Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="bg-muted/60 text-left text-xs text-muted-foreground"><tr><th className="p-4">พนักงาน</th><th className="p-4">อีเมล</th><th className="p-4">บทบาท</th><th className="p-4">สาขา</th><th className="p-4 text-right">จัดการ</th></tr></thead><tbody>{users.map((user)=><tr key={user.id} className="border-t"><td className="p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-secondary text-primary"><UserRound className="size-4"/></span><strong>{user.name}</strong></div></td><td className="p-4 text-muted-foreground"><span className="flex items-center gap-2"><Mail className="size-4"/>{user.email}</span></td><td className="p-4"><select aria-label={`บทบาทของ ${user.name}`} className="min-h-10 rounded-lg border bg-card px-2" value={user.role} onChange={(e)=>saveUser({...user,role:e.target.value as UserRole,updatedAt:new Date().toISOString()})}>{["OWNER","MANAGER","CASHIER","KITCHEN","BAR"].map((item)=><option key={item}>{item}</option>)}</select></td><td className="p-4">สุขุมวิท</td><td className="p-4 text-right"><Button variant="ghost" size="icon" aria-label={`ลบ ${user.name}`} disabled={user.role==="OWNER"} onClick={()=>{if(confirm(`ลบ ${user.name}?`))removeUser(user.id)}}><Trash2/></Button></td></tr>)}</tbody></table></div></Card><Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>เพิ่มพนักงาน</DialogTitle><DialogDescription>บัญชีนี้เป็นข้อมูลจำลองและยังไม่มีระบบส่งคำเชิญจริง</DialogDescription></DialogHeader><form onSubmit={add} className="space-y-4"><div className="space-y-2"><Label htmlFor="employee-name">ชื่อ</Label><Input id="employee-name" value={name} onChange={(e)=>setName(e.target.value)} required/></div><div className="space-y-2"><Label htmlFor="employee-email">อีเมล</Label><Input id="employee-email" type="email" value={email} onChange={(e)=>setEmail(e.target.value)} required/></div><div className="space-y-2"><Label htmlFor="employee-role">บทบาท</Label><select id="employee-role" className="min-h-11 w-full rounded-lg border bg-card px-3" value={role} onChange={(e)=>setRole(e.target.value as UserRole)}>{["MANAGER","CASHIER","KITCHEN","BAR"].map((item)=><option key={item}>{item}</option>)}</select></div><DialogFooter><Button type="button" variant="outline" onClick={()=>setOpen(false)}>ยกเลิก</Button><Button type="submit">เพิ่มพนักงาน</Button></DialogFooter></form></DialogContent></Dialog></>;
}
